on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
name: Mirror BioSisyphus GitHub Repo to Gitee
jobs:
  run:
    name: Sync-Gitee
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source codes
      uses: actions/checkout@v1
    - name: Mirror the Github organization repos to Gitee.
      uses: flyingcys/sync2gitee@master
      with:
        src: github/flyingcys
        dst: gitee/flyingcys
        dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
        dst_token: ${{ secrets.GITEE_TOKEN }}
        account_type: org
        force_update: true
